version: '2'
services:
  ### Application
  web:
    restart: always
    build: ./application/
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    env_file: env
    volumes:
      - /home/wger/static
    depends_on:
      - postgres
      - redis

  ### Reverse proxy
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes_from:
      - web
    links:
      - web:web

  ### Database
  postgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - data
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backups/postgresql:/backup
    env_file:
      - env
    expose:
      - "5432"

  ### Cache
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"

  ### Data volume
  data:
    restart: always
    image: alpine
    volumes:
      - /var/lib/postgresql
    command: "true"
